version: "3.9"

services:
  pg_db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=booking_db
      - POSTGRES_USER=Marina
      - POSTGRES_PASSWORD=events
    volumes:
      - db:/var/lib/postgresql/data postgres
    ports:
      - "5455:5432"

volumes:
  db:

